### ISSUE TITLE
Make title icon clickable to return to homepage (when not in game)

### ISSUE THREAD

**Issue by kajgrant** [ConorMurphy21/StrikeOrSike#156]
- The main 'Strike or Sike' title image should be clickable
- When clicked, the title should return the user to the main home page
- Should allow the user to navigate back to the home page when on sub-pages like the 'About' or 'How to Play pages'

**Comment by ConorMurphy21** [comment]
My concern with this is that it adds the possibility to accidentally kick yourself from the game room. Since we don't use cookies yet, this could potentially cause people to re-enter the room they were in. Maybe this feature should only be enabled if the scene is 'how-to-play' or 'about' but not if it is 'game'.
